### ISSUE TITLE
One project per page

### ISSUE THREAD

**Issue by sponte** [oss-specs/specs#100] opened 2015-09-04 09:09 UTC
Currently we have all projects displayed on the features page, they are separated by a header within a page. I think there is not much value in combining multiple projects on one page. @jimCresswell what do you think?

**Comment by jimCresswell** [comment] 2015-09-04 09:52
I think it's a duplicate of #98 :wink:

**Comment by jimCresswell** [comment] 2015-09-04 15:05
Closing as duplicate.

**Closed by jimCresswell** 2015-09-04 15:05 UTC
Labels: duplicate
